export const environment = {
  production: true,
  APP_TITLE: 'Fish category PROD',
  PATH_FISHES: '/fishes',
  FISHES: 'fishes',
  FISH_ID: 'fishId',
  PATH_MAIN: '',
  POST_METHOD: 'POST',
  BEARER_NAME: 'Bearer',
  PATH_FISH_DETAIL: 'fish/:fishId',
  PATH_FISH_ADD: 'addFish',
  REST_API_URL: 'http://localhost:3000/api',
  GETALL_URL: '/fishes?search=',
  COUNT_DEFAULT_VALUE: 8,
  QUERY_OFFSET: '&offset=',
  QUERY_COUNT: '&count=',
  GET_FISH_URL: '/fishes/',
  PATH_DIST: '/fishes',
  USERS_API_URL: '/users',
  USERS_LOGIN_URL: '/users/login',
  SEARCH_QUERY_PARAM: 'search',
  TOKEN_STORAGE_KEY: 'games_token',
  DUMMY_NAME: 'Dummy',
  FISH_ADDED_SUCCESS: 'Fish saved successfully!',
  FISH_ADD_FAILED: 'Failed to add a fish!',
  FISH_UPDATED_SUCCESS: 'Fish updated successfully!',
  FISH_UPDATE_FAILED: 'Failed to update a fish!',
  INCORRECT_CREDENTIALS: 'Username or password incorrect!',
  LOGIN_SUCCESS: 'Successfully logged in!',
  PATH_HOME: '',
  PATH_EDIT_FISH: 'fish/:fishId',
  PATH_ADD_FISH: 'addFish',
  PATH_FISHS: 'fishes',
  PATH_REGISTER: 'register',
  PATH_PROFILE: 'profile',
  PATH_ERROR: '**',
};
