export const environment = {
  production: true,
  APP_TITLE: 'Fish category PROD',
  PATH_FISHES: '/fishes',
  FISHES: 'fishes',
  FISH_ID: 'fishId',
  PATH_MAIN: '',
  PATH_FISH_DETAIL: 'fish/:fishId',
  PATH_FISH_ADD: 'addFish',
  REST_API_URL: 'http://localhost:3000/api',
  GETALL_URL: '/fishes?search=',
  COUNT_QUERY_PARAM: '&count=6',
  GET_FISH_URL: '/fishes/',
  PATH_DIST: '/fishes',
  SEARCH_QUERY_PARAM: 'search',
  TOKEN_STORAGE_KEY: 'games_token',
};
